{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{if $attribute.has_content}
<table>
<tr><th class="table_no_border">{'Title'|i18n( 'design/standard/content/datatype' )}:</th><td class="table_no_border">{$attribute.content.title|wash()}</td></tr>
<tr><th class="table_no_border">{'Description'|i18n( 'design/standard/content/datatype' )}:</th><td class="table_no_border">{$attribute.content.description|wash()}</td></tr>
<tr><th class="table_no_border">{'Keywords'|i18n( 'design/standard/content/datatype' )}:</th><td class="table_no_border">{$attribute.content.keywords|implode( ', ' )|wash()}</td></tr>

<tr><th class="table_no_border">{'Use in sitemap'|i18n( 'design/standard/content/datatype' )}:</th><td class="table_no_border">{if eq($attribute.content.sitemap_use,'1')}{'yes'|i18n( 'design/standard/class/datatype' )}{else}{'no'|i18n( 'design/standard/class/datatype' )}{/if}</td></tr>
<tr><th class="table_no_border">{'Change frequence'|i18n( 'design/standard/content/datatype' )}:</th><td class="table_no_border">{$attribute.content.change|wash()|i18n( 'design/standard/class/datatype' )}</td></tr>
<tr><th class="table_no_border">{'Priority'|i18n( 'design/standard/content/datatype' )}:</th><td class="table_no_border">{$attribute.content.priority|wash()}</td></tr>

</table>
{/if}
